version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
    - image: circleci/python:3.7-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Setup testing environment
          command: |
            pip3 install '.[test]' --user
            pip3 install coverage pytest
            echo $HOME
      - run:
          name: Run Tests
          command: |
            coverage run -m pytest       
      - run:
          name: Coverage Reports
          when: on_fail
          command: |
            coverage report
            coverage html
      - codecov/upload:
          file: htmlcov/codecov.html
          flags: pytest-coverage
      - store_artifacts:
          path: htmlcov
workflows:
  version: 2
  workflow:
    jobs:
      - build

